#!/bin/sh
set -e
# Automatically added by dh_usrlocal/12.1.1~bpo9+1
(
	while read dir; do
		rmdir "$dir" 2>/dev/null || true
	done
) << DATA
/usr/local/share/man/man1
/usr/local/share/man
DATA
# End automatically added section
